### ISSUE TITLE
Fullfil Inaka's open-source checklist

### ISSUE THREAD

**Issue by elbrujohalcon** [inaka/tele_sign#1]
From [Inaka's wiki](https://github.com/inaka/inaka_corp/wiki/Open-Source-checklist):

## General Items
- [x] It has a github repo
- [x] It has a proper LICENSE file
- [x] It's hooked to a hipchat room
- [ ] It's has a clear and useful README.md
- [ ] It's documented (with examples)
- [ ] It's tested

## Exhibition
- [ ] There is a blog post about it
- [ ] It's shared on social networks

## For node projects
- [ ] Publish as a npm package
